- name: Add vscode gpg key 
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc


- name: Add vsode repository 
  yum_repository:
    name: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    description: RPM YUM repo for vscode

- name: Install vscode dnf
  dnf: 
    state: latest
    name: code